on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: 2022
          run: |
            date
            pwd
            ls -al 
            df -h
            ./xake compilePdf complexe_getallen/cmplx_norm.tex